### ROI에 의한 블록 평균 영상

In [1]:
import cv2
import numpy as np

In [2]:
src = cv2.imread('./data/lena.jpg',cv2.IMREAD_GRAYSCALE)
dst = np.zeros(src.shape,dtype=src.dtype)
src

array([[163, 162, 161, ..., 170, 154, 130],
       [162, 162, 162, ..., 173, 155, 126],
       [162, 162, 163, ..., 170, 155, 128],
       ...,
       [ 43,  42,  51, ..., 103, 101,  99],
       [ 41,  42,  55, ..., 103, 105, 106],
       [ 42,  44,  57, ..., 102, 106, 109]], dtype=uint8)

In [3]:
print(src.shape) #크기
print(src.ndim) #차원

(512, 512)
2


In [4]:
dst = np.zeros(src.shape,dtype=src.dtype)
dst

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [5]:
N = 32
height,width = src.shape #512

In [6]:
h= height // N
h

16

In [7]:
w = width // N
w

16

In [8]:
for i in range(N):
    for j in range(N):
        y=i*h
        x=j*w
        roi = src[y:y+h,x:x+w]
        dst[y:y+h,x:x+w] = cv2.mean(roi)[0]
dst

array([[158, 158, 158, ..., 101, 101, 101],
       [158, 158, 158, ..., 101, 101, 101],
       [158, 158, 158, ..., 101, 101, 101],
       ...,
       [ 64,  64,  64, ...,  64,  64,  64],
       [ 64,  64,  64, ...,  64,  64,  64],
       [ 64,  64,  64, ...,  64,  64,  64]], dtype=uint8)

In [9]:
cv2.imshow('dst',dst[:])
cv2.waitKey()
cv2.destroyAllWindows()