### 영상연산 : 비트연산1

In [11]:
import cv2
import numpy as np
src1 = cv2.imread('./data/lena.jpg',cv2.IMREAD_GRAYSCALE)
src2 = np.zeros(shape=(512,512),dtype=np.uint8)+100

#### 타겟 이미지

In [12]:
dst1 = src1 + src2 #원하지 않는 255이 넘어가는 값을 0부터 다시 시작함
print(dst1)
dst2 = cv2.add(src1,src2)
print(dst2)
dst3 =cv2.add(src1,src2,dtype=cv2.CV_8U)
print(dst3)

[[  7   6   5 ...  14 254 230]
 [  6   6   6 ...  17 255 226]
 [  6   6   7 ...  14 255 228]
 ...
 [143 142 151 ... 203 201 199]
 [141 142 155 ... 203 205 206]
 [142 144 157 ... 202 206 209]]
[[255 255 255 ... 255 254 230]
 [255 255 255 ... 255 255 226]
 [255 255 255 ... 255 255 228]
 ...
 [143 142 151 ... 203 201 199]
 [141 142 155 ... 203 205 206]
 [142 144 157 ... 202 206 209]]
[[255 255 255 ... 255 254 230]
 [255 255 255 ... 255 255 226]
 [255 255 255 ... 255 255 228]
 ...
 [143 142 151 ... 203 201 199]
 [141 142 155 ... 203 205 206]
 [142 144 157 ... 202 206 209]]


In [13]:
dst3 = ~dst3 #반전영상

In [14]:
cv2.imshow('dst1',dst1)
cv2.imshow('dst2',dst2)
cv2.imshow('dst3',dst3)

cv2.waitKey()
cv2.destroyAllWindows()