In [11]:
from keras.models import Sequential
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder

import pandas as pd
import numpy
import tensorflow as tf

Using TensorFlow backend.


In [12]:
np.random.seed(3)
tf.random.set_seed(3)

In [13]:
df = pd.read_csv('./dataset/sonar.csv',header=None)
df

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0090  0.0032   R  
1    0.0052  0.0044   R  
2    0.0095  0.0078   R  
3    0.0040  0.0117   R  
4    0.0107  0.0094   R  
..      ...     ...  ..  
203  0.0193  0.0157   M  
204  0.0062  0.0067   M  
205  0.0077  0.0031   M  
206  0.0036  0.0048   M  
207  0.0061  0.0115   M  

[208 rows x 61 columns]

In [14]:
df.describe()

0           1           2           3           4           5   \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.029164    0.038437    0.043832    0.053892    0.075202    0.104570   
std      0.022991    0.032960    0.038428    0.046528    0.055552    0.059105   
min      0.001500    0.000600    0.001500    0.005800    0.006700    0.010200   
25%      0.013350    0.016450    0.018950    0.024375    0.038050    0.067025   
50%      0.022800    0.030800    0.034300    0.044050    0.062500    0.092150   
75%      0.035550    0.047950    0.057950    0.064500    0.100275    0.134125   
max      0.137100    0.233900    0.305900    0.426400    0.401000    0.382300   

               6           7           8           9   ...          50  \
count  208.000000  208.000000  208.000000  208.000000  ...  208.000000   
mean     0.121747    0.134799    0.178003    0.208259  ...    0.016069   
std      0.061788    0.085152    0.118387    0.134416  ...    0.012008   
min      0.003300    0.005500    0.007500    0.011300  ...    0.000000   
25%      0.080900    0.080425    0.097025    0.111275  ...    0.008425   
50%      0.106950    0.112100    0.152250    0.182400  ...    0.013900   
75%      0.154000    0.169600    0.233425    0.268700  ...    0.020825   
max      0.372900    0.459000    0.682800    0.710600  ...    0.100400   

               51          52          53          54          55          56  \
count  208.000000  208.000000  208.000000  208.000000  208.000000  208.000000   
mean     0.013420    0.010709    0.010941    0.009290    0.008222    0.007820   
std      0.009634    0.007060    0.007301    0.007088    0.005736    0.005785   
min      0.000800    0.000500    0.001000    0.000600    0.000400    0.000300   
25%      0.007275    0.005075    0.005375    0.004150    0.004400    0.003700   
50%      0.011400    0.009550    0.009300    0.007500    0.006850    0.005950   
75%      0.016725    0.014900    0.014500    0.012100    0.010575    0.010425   
max      0.070900    0.039000    0.035200    0.044700    0.039400    0.035500   

               57          58          59  
count  208.000000  208.000000  208.000000  
mean     0.007949    0.007941    0.006507  
std      0.006470    0.006181    0.005031  
min      0.000300    0.000100    0.000600  
25%      0.003600    0.003675    0.003100  
50%      0.005800    0.006400    0.005300  
75%      0.010350    0.010325    0.008525  
max      0.044000    0.036400    0.043900  

[8 rows x 60 columns]

In [15]:
dataset = df.values
dataset

array([[0.02, 0.0371, 0.0428, ..., 0.009, 0.0032, 'R'],
       [0.0453, 0.0523, 0.0843, ..., 0.0052, 0.0044, 'R'],
       [0.0262, 0.0582, 0.1099, ..., 0.0095, 0.0078, 'R'],
       ...,
       [0.0522, 0.0437, 0.018, ..., 0.0077, 0.0031, 'M'],
       [0.0303, 0.0353, 0.049, ..., 0.0036, 0.0048, 'M'],
       [0.026, 0.0363, 0.0136, ..., 0.0061, 0.0115, 'M']], dtype=object)

In [16]:
X = dataset[:,0:60]
print(X)
Y_obj = dataset[:,60]
print(Y_obj)

[[0.02 0.0371 0.0428 ... 0.0084 0.009 0.0032]
 [0.0453 0.0523 0.0843 ... 0.0049 0.0052 0.0044]
 [0.0262 0.0582 0.1099 ... 0.0164 0.0095 0.0078]
 ...
 [0.0522 0.0437 0.018 ... 0.0138 0.0077 0.0031]
 [0.0303 0.0353 0.049 ... 0.0079 0.0036 0.0048]
 [0.026 0.0363 0.0136 ... 0.0036 0.0061 0.0115]]
['R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M'
 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 'M' 

In [17]:
#### 변환
e = LabelEncoder()
e.fit(Y_obj)
Y = e.transform(Y_obj)

In [18]:
model = Sequential()
model.add(Dense(24,input_dim=60,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [19]:
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])

In [20]:
model.fit(X, Y, epochs=200, batch_size=5) # 과적합

Epoch 1/200
208/208 [==============================] - 0s 596us/step - loss: 0.2449 - accuracy: 0.5673
Epoch 2/200
208/208 [==============================] - 0s 179us/step - loss: 0.2404 - accuracy: 0.5481
Epoch 3/200
208/208 [==============================] - 0s 166us/step - loss: 0.2268 - accuracy: 0.6202
Epoch 4/200
208/208 [==============================] - 0s 168us/step - loss: 0.2185 - accuracy: 0.6394
Epoch 5/200
208/208 [==============================] - 0s 175us/step - loss: 0.2103 - accuracy: 0.6971
Epoch 6/200
208/208 [==============================] - 0s 175us/step - loss: 0.2016 - accuracy: 0.7260
Epoch 7/200
208/208 [==============================] - 0s 158us/step - loss: 0.1937 - accuracy: 0.7356
Epoch 8/200
208/208 [==============================] - 0s 173us/step - loss: 0.1849 - accuracy: 0.7788
Epoch 9/200
208/208 [==============================] - 0s 182us/step - loss: 0.1777 - accuracy: 0.7788
Epoch 10/200
208/208 [==============================] - 0s 168us/step - l

208/208 [==============================] - 0s 173us/step - loss: 0.0235 - accuracy: 0.9808
Epoch 80/200
208/208 [==============================] - 0s 167us/step - loss: 0.0246 - accuracy: 0.9808
Epoch 81/200
208/208 [==============================] - 0s 160us/step - loss: 0.0237 - accuracy: 0.9760
Epoch 82/200
208/208 [==============================] - 0s 171us/step - loss: 0.0237 - accuracy: 0.9856
Epoch 83/200
208/208 [==============================] - 0s 158us/step - loss: 0.0219 - accuracy: 0.9856
Epoch 84/200
208/208 [==============================] - 0s 169us/step - loss: 0.0206 - accuracy: 0.9808
Epoch 85/200
208/208 [==============================] - 0s 172us/step - loss: 0.0205 - accuracy: 0.9856
Epoch 86/200
208/208 [==============================] - 0s 171us/step - loss: 0.0195 - accuracy: 0.9856
Epoch 87/200
208/208 [==============================] - 0s 169us/step - loss: 0.0183 - accuracy: 0.9856
Epoch 88/200
208/208 [==============================] - 0s 168us/step - loss:

208/208 [==============================] - 0s 167us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 158/200
208/208 [==============================] - 0s 162us/step - loss: 0.0012 - accuracy: 1.0000
Epoch 159/200
208/208 [==============================] - 0s 169us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 160/200
208/208 [==============================] - 0s 160us/step - loss: 0.0011 - accuracy: 1.0000
Epoch 161/200
208/208 [==============================] - 0s 158us/step - loss: 0.0010 - accuracy: 1.0000
Epoch 162/200
208/208 [==============================] - 0s 161us/step - loss: 8.5618e-04 - accuracy: 1.0000
Epoch 163/200
208/208 [==============================] - 0s 160us/step - loss: 8.7159e-04 - accuracy: 1.0000
Epoch 164/200
208/208 [==============================] - 0s 163us/step - loss: 8.6171e-04 - accuracy: 1.0000
Epoch 165/200
208/208 [==============================] - 0s 174us/step - loss: 8.5474e-04 - accuracy: 1.0000
Epoch 166/200
208/208 [==============================