#1.학습모델 저장
#2.train 데이터와 test 데이터 분리

In [32]:
from keras.models import Sequential,load_model
from keras.layers.core import Dense
from sklearn.preprocessing import LabelEncoder

import pandas as pd
import numpy as np
import numpy
import tensorflow as tf

In [20]:
seed = 0

np.random.seed(3)
tf.random.set_seed(3)

In [5]:
df = pd.read_csv('./dataset/sonar.csv',header=None)
df

0       1       2       3       4       5       6       7       8   \
0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109   
1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337   
2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598   
3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598   
4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564   
..      ...     ...     ...     ...     ...     ...     ...     ...     ...   
203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328   
204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030   
205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258   
206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945   
207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843   

         9   ...      51      52      53      54      55      56      57  \
0    0.2111  ...  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180  0.0084   
1    0.2872  ...  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140  0.0049   
2    0.6194  ...  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316  0.0164   
3    0.1264  ...  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050  0.0044   
4    0.4459  ...  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072  0.0048   
..      ...  ...     ...     ...     ...     ...     ...     ...     ...   
203  0.2684  ...  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065  0.0115   
204  0.2154  ...  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034  0.0032   
205  0.2529  ...  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140  0.0138   
206  0.2354  ...  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034  0.0079   
207  0.2354  ...  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040  0.0036   

         58      59  60  
0    0.0090  0.0032   R  
1    0.0052  0.0044   R  
2    0.0095  0.0078   R  
3    0.0040  0.0117   R  
4    0.0107  0.0094   R  
..      ...     ...  ..  
203  0.0193  0.0157   M  
204  0.0062  0.0067   M  
205  0.0077  0.0031   M  
206  0.0036  0.0048   M  
207  0.0061  0.0115   M  

[208 rows x 61 columns]

In [7]:
dataset = df.values
x = dataset[:,0:60]
y_obj = dataset[:,60]

In [8]:
y_obj

array(['R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M',
       'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M

In [16]:
X = dataset[:,0:60]
e = LabelEncoder()
e.fit(y_obj)
Y = e.transform(y_obj)

In [12]:
# print(e)
print(Y)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


### 회귀?인지 분류?인지

In [13]:
model = Sequential()
model.add(Dense(24,input_dim=60,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [14]:
model.compile(loss='mean_squared_error',optimizer='adam',metrics=['accuracy'])

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3, random_state=seed)

In [23]:
X_train

array([[0.0135, 0.0045, 0.0051, ..., 0.0028, 0.003, 0.003],
       [0.0293, 0.0644, 0.039, ..., 0.016, 0.0095, 0.0011],
       [0.024, 0.0218, 0.0324, ..., 0.0019, 0.0066, 0.0023],
       ...,
       [0.0228, 0.0106, 0.013, ..., 0.0045, 0.0063, 0.0039],
       [0.0373, 0.0281, 0.0232, ..., 0.0054, 0.0085, 0.006],
       [0.018, 0.0444, 0.0476, ..., 0.005, 0.0073, 0.0022]], dtype=object)

In [24]:
X_test

array([[0.0079, 0.0086, 0.0055, ..., 0.0058, 0.0059, 0.0032],
       [0.0229, 0.0369, 0.004, ..., 0.0029, 0.0104, 0.0163],
       [0.0442, 0.0477, 0.0049, ..., 0.0105, 0.0059, 0.0105],
       ...,
       [0.0315, 0.0252, 0.0167, ..., 0.0035, 0.0001, 0.0055],
       [0.0428, 0.0555, 0.0708, ..., 0.0084, 0.0113, 0.0049],
       [0.0239, 0.0189, 0.0466, ..., 0.0026, 0.0036, 0.0024]],
      dtype=object)

In [25]:
Y_train

array([1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0])

In [26]:
Y_test

array([1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1])

In [27]:
# 학습셋,테스트셋 분류
model.fit(X_train,Y_train,epochs=130,batch_size=10)

Epoch 1/130
145/145 [==============================] - 0s 653us/step - loss: 0.2476 - accuracy: 0.5724
Epoch 2/130
145/145 [==============================] - 0s 124us/step - loss: 0.2407 - accuracy: 0.5379
Epoch 3/130
145/145 [==============================] - 0s 103us/step - loss: 0.2360 - accuracy: 0.5310
Epoch 4/130
145/145 [==============================] - 0s 96us/step - loss: 0.2296 - accuracy: 0.6138
Epoch 5/130
145/145 [==============================] - 0s 96us/step - loss: 0.2235 - accuracy: 0.6759
Epoch 6/130
145/145 [==============================] - 0s 103us/step - loss: 0.2210 - accuracy: 0.6207
Epoch 7/130
145/145 [==============================] - 0s 97us/step - loss: 0.2152 - accuracy: 0.6483
Epoch 8/130
145/145 [==============================] - 0s 96us/step - loss: 0.2097 - accuracy: 0.7103
Epoch 9/130
145/145 [==============================] - 0s 103us/step - loss: 0.2049 - accuracy: 0.7310
Epoch 10/130
145/145 [==============================] - 0s 96us/step - loss: 

145/145 [==============================] - 0s 83us/step - loss: 0.0440 - accuracy: 0.9655
Epoch 81/130
145/145 [==============================] - 0s 83us/step - loss: 0.0415 - accuracy: 0.9724
Epoch 82/130
145/145 [==============================] - 0s 96us/step - loss: 0.0418 - accuracy: 0.9724
Epoch 83/130
145/145 [==============================] - 0s 96us/step - loss: 0.0393 - accuracy: 0.9724
Epoch 84/130
145/145 [==============================] - 0s 89us/step - loss: 0.0457 - accuracy: 0.9517
Epoch 85/130
145/145 [==============================] - 0s 83us/step - loss: 0.0481 - accuracy: 0.9724
Epoch 86/130
145/145 [==============================] - 0s 89us/step - loss: 0.0411 - accuracy: 0.9586
Epoch 87/130
145/145 [==============================] - 0s 89us/step - loss: 0.0391 - accuracy: 0.9862
Epoch 88/130
145/145 [==============================] - 0s 89us/step - loss: 0.0394 - accuracy: 0.9655
Epoch 89/130
145/145 [==============================] - 0s 84us/step - loss: 0.0384 - 

## 훈련모델저장

In [28]:
model.save('myModel.h5')

In [29]:
del model

#### 모델불러오기

In [33]:
model = load_model('myModel.h5')

In [37]:
model.evaluate(X_test,Y_test)[1]

63/63 [==============================] - 0s 47us/step


0.8730158805847168